debug:
  config: true
  chance: false
  drops: true
  allow_spawn_eggs: false

looting_base: 1.3

world:
  # Per-world drop chance multiplier (all drops); compensates for the end grinder.
  factor:
    testing: 1.0
    world: 1.0
    world_nether: 1.0
    world_the_end: 0.01

drops:
  head:
    enabled: true
    chance: 0.005

    # Mob type specific factor multiplied by the base head drop chance.
    # If the mob is not listed, then the factor defaults to 1.0.
    # Note, however, that spawner mobs don't do special drops.
    # For the purposes of this config, we're setting the drop rate of anything
    # that can be relatively easily farmed (i.e. animals, slimes, villagers and
    # guardians) at 1/10th that of hostile mobs.
    scale:
      CHICKEN: 0.2
      COW: 0.2
      ENDER_DRAGON: 20001.0
      GUARDIAN: 0.1
      GOLEM: 0.2
      HORSE: 0.2
      MAGMA_CUBE: 3.0
      MUSHROOM_COW: 0.2
      OCELOT: 0.2
      PIG: 0.2
      POLAR_BEAR: 5.0
      RABBIT: 0.2
      SHEEP: 0.2
      SLIME: 3.0
      SNOW_GOLEM: 0.2
      SQUID: 1.0
      VILLAGER: 0.2
      # Wither skeletons drop their heads naturally.
      WITHER_SKELETON: 0.0
      WOLF: 0.2

    # Skull owners for head drops, or missing for no skull.
    # texture data instead of the owner, in a later version.
    # Any mob that doesn't have an entry won't drop a skull,
    # e.g. WITHER_SKELETON.
    owner:
      BLAZE: MHF_Blaze
      CAVE_SPIDER: MHF_CaveSpider
      CHICKEN: MHF_Chicken
      COW: MHF_Cow
      ENDERMAN: MHF_Enderman
      ENDERMITE: MHF_Endermite
      GHAST: MHF_Ghast
      GOLEM: MHF_Golem
      GUARDIAN: MHF_Guardian
      # HORSE: doesn't exist
      # HUSK: MHF_Husk doesn't look like a husk
      MAGMA_CUBE: MHF_LavaSlime
      MUSHROOM_COW: MHF_MushroomCow
      OCELOT: MHF_Ocelot
      PIG: MHF_Pig
      PIG_ZOMBIE: MHF_PigZombie
      POLAR_BEAR: MHF_PolarBear
      RABBIT: MHF_Rabbit
      SHEEP: MHF_Sheep
      SHULKER: MHF_Shulker
      # SILVERFISH: shows as a pumpkin :(
      SLIME: MHF_Slime
      SNOW_GOLEM: MHF_SnowGolem
      SPIDER: MHF_Spider
      STRAY: MHF_Stray
      SQUID: MHF_Squid
      VILLAGER: MHF_Villager
      WITCH: MHF_Witch
      WITHER: MHF_Wither
      WOLF: MHF_Wolf

  essence_of_flight:
    enabled: true
    chance: 0.001
    item:
      ==: org.bukkit.inventory.ItemStack
      type: GHAST_TEAR
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: ยง6Essence of Flight
        lore:
        - ยง9Craft along with a Dragon Head for an Elytra!
        enchants:
          ARROW_KNOCKBACK: 10

    # Mob type specific factor multiplied by the base EoF drop chance.
    # If the mob is not listed, then the factor defaults to 0.0.
    # Note, however, that spawner mobs don't do special drops.
    scale:
      BAT: 10.0
      BLAZE: 10.0
      CAVE_SPIDER: 1.0
      CREEPER: 2.0
      ENDER_DRAGON: 50000.0
      ENDERMAN: 1.0
      ENDERMITE: 3.0
      GHAST: 10.0
      GUARDIAN: 0.01
      HUSK: 0.5
      MAGMA_CUBE: 2.0
      PIG_ZOMBIE: 0.5
      SILVERFISH: 3.0
      SLIME: 0.5
      SHULKER: 2.0
      SKELETON: 0.5
      SPIDER: 1.0
      STRAY: 0.5
      WITCH: 5.0
      WITHER: 10.0
      ZOMBIE: 0.5
