name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: io.totemo.gonebatty.GoneBatty
depend: [EntityMeta]
api-version: 1.13

permissions:
  gonebatty.admin:
    description: Permission to administer the plugin.
    default: op

commands:
  gonebatty:
    description: ${project.name} administrative command.
    permission: gonebatty.admin
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> reload§f - Reload the configuration.
      §e/<command> set-head <type>§f - Set the head for the specified mob type to the item in your hand. Use an empty hand to clear. Mob type constants are listed at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html.
      §e/<command> get-head <type>§f - Get the head for the specified mob type.
      §e/<command> list-heads§f - List all the configured head types, colour coded green (item) or red (no configured item).
